sudo: required
services:
  - docker

before_install:
  - docker build -t nashno9/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nashno9/react-test npm run test 

after_success:
  - docker build -t nashno9/multi-client ./client
  - docker build -t nashno9/multi-nginx ./nginx
  - docker build -t nashno9/multi-server ./server
  - docker build -t nashno9/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nashno9/multi-client
  - docker push nashno9/multi-nginx
  - docker push nashno9/multi-server
  - docker push nashno9/multi-worker

deploy:
  provider: elasicbeanstalk
  region: us-west-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-west-1-894566283821
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY